const _ = require('lodash')
const { run } = require('./utils')
const S = require('./statistics')

run(function*({ Com }) {
  const docs = yield Com.find({'stats.member_count': {$ne: null}}, {'stats': 1})
  const data = docs.map(doc => doc.stats.member_count)
  console.log('平均 : ', S.average(data))
  console.log('分散 : ', S.dispersion(data))
  console.log('標準偏差 : ', S.standardDeviation(data))
  console.log('')
  console.log('偏差値 : co54638 : ', S.deviation(23103, data))
  console.log('偏差値 : co3061611 : ', S.deviation(43, data))
  console.log('偏差値 : 2人コミュ : ', S.deviation(2, data))
  console.log('')
  const st = S.sturges(data)
  console.log('スタージス級数 : ', st.m)
  console.log('等級間隔 : ', st.c)
})
